<?php

class Auth extends Laravel\Auth{};
class_alias('Auth', 'Laravel\Auth');
class Authenticator extends Laravel\Auth\Drivers\Driver{};
class_alias('Authenticator', 'Laravel\Auth\Drivers\Driver');
class Asset extends Laravel\Asset{};
class_alias('Asset', 'Laravel\Asset');
class Autoloader extends Laravel\Autoloader{};
class_alias('Autoloader', 'Laravel\Autoloader');
class Blade extends Laravel\Blade{};
class_alias('Blade', 'Laravel\Blade');
class Bundle extends Laravel\Bundle{};
class_alias('Bundle', 'Laravel\Bundle');
class Cache extends Laravel\Cache{};
class_alias('Cache', 'Laravel\Cache');
class Config extends Laravel\Config{};
class_alias('Config', 'Laravel\Config');
class Controller extends Laravel\Routing\Controller{};
class_alias('Controller', 'Laravel\Routing\Controller');
class Cookie extends Laravel\Cookie{};
class_alias('Cookie', 'Laravel\Cookie');
class Crypter extends Laravel\Crypter{};
class_alias('Crypter', 'Laravel\Crypter');
class DB extends Laravel\Database{};
class_alias('DB', 'Laravel\Database');
class Eloquent extends Laravel\Database\Eloquent\Model{};
class_alias('Eloquent', 'Laravel\Database\Eloquent\Model');
class Event extends Laravel\Event{};
class_alias('Event', 'Laravel\Event');
class File extends Laravel\File{};
class_alias('File', 'Laravel\File');
class Filter extends Laravel\Routing\Filter{};
class_alias('Filter', 'Laravel\Routing\Filter');
class Form extends Laravel\Form{};
class_alias('Form', 'Laravel\Form');
class Hash extends Laravel\Hash{};
class_alias('Hash', 'Laravel\Hash');
class HTML extends Laravel\HTML{};
class_alias('HTML', 'Laravel\HTML');
class Input extends Laravel\Input{};
class_alias('Input', 'Laravel\Input');
class IoC extends Laravel\IoC{};
class_alias('IoC', 'Laravel\IoC');
class Lang extends Laravel\Lang{};
class_alias('Lang', 'Laravel\Lang');
class Log extends Laravel\Log{};
class_alias('Log', 'Laravel\Log');
class Memcached extends Laravel\Memcached{};
class_alias('Memcached', 'Laravel\Memcached');
class Paginator extends Laravel\Paginator{};
class_alias('Paginator', 'Laravel\Paginator');
class Profiler extends Laravel\Profiling\Profiler{};
class_alias('Profiler', 'Laravel\Profiling\Profiler');
class URL extends Laravel\URL{};
class_alias('URL', 'Laravel\URL');
class Redirect extends Laravel\Redirect{};
class_alias('Redirect', 'Laravel\Redirect');
class Redis extends Laravel\Redis{};
class_alias('Redis', 'Laravel\Redis');
class Request extends Laravel\Request{};
class_alias('Request', 'Laravel\Request');
class Response extends Laravel\Response{};
class_alias('Response', 'Laravel\Response');
class Route extends Laravel\Routing\Route{};
class_alias('Route', 'Laravel\Routing\Route');
class Router extends Laravel\Routing\Router{};
class_alias('Router', 'Laravel\Routing\Router');
class Schema extends Laravel\Database\Schema{};
class_alias('Schema', 'Laravel\Database\Schema');
class Section extends Laravel\Section{};
class_alias('Section', 'Laravel\Section');
class Session extends Laravel\Session{};
class_alias('Session', 'Laravel\Session');
class Str extends Laravel\Str{};
class_alias('Str', 'Laravel\Str');
class Task extends Laravel\CLI\Tasks\Task{};
class_alias('Task', 'Laravel\CLI\Tasks\Task');
class URI extends Laravel\URI{};
class_alias('URI', 'Laravel\URI');
class Validator extends Laravel\Validator{};
class_alias('Validator', 'Laravel\Validator');
class View extends Laravel\View{};
class_alias('View', 'Laravel\View');